### ISSUE TITLE
基于注解的脱敏比较消耗性能，需要添加基于slf4j的日志脱敏（或者基于ASM字节优化）

### ISSUE THREAD

**Issue by houbb** [houbb/sensitive#1]
基于注解的脱敏比较消耗性能，需要添加基于slf4j的日志脱敏

**Comment by giantzhang** [comment]
您好，T desCopy(T object)只支持单个对象的属性脱敏对吧？我补充个处理List<T> desCopyList(List<T> srclist)的方法可以吗？循环调用下现有的desCopy(T object)。

**Comment by houbb** [comment]
嗯，你可以尝试下集合。如果不行的话，可以提 issues，也欢迎 PR。

如果 pr 建议可以提供 desCopyIterable 或者 desCopyCollection，应用范围更广一些。^_^

**Comment by jiangeeq** [comment]
基于slf4j的日志脱敏（或者基于ASM字节优化）

**Comment by jiangeeq** [comment]
期待这个---基于slf4j的日志脱敏（或者基于ASM字节优化）

**Comment by singAllSong** [comment]
可以加条用户地址的敏感策略吗

**Comment by houbb** [comment]
> 可以加条用户地址的敏感策略吗

可以的。这个另外提一个 issue，说下具体的要求，如果适用性较广，可以支持。

所有的注解都支持自定义，也可以自己添加。

**Comment by lyl9816** [comment]
建议长数字加密可以让用户自定义脱敏的位数，只有二代身份证号脱敏加密的话，太具有针对性了，像银行卡号、工号之类的可以传参设置脱敏位数

**Comment by houbb** [comment]
> 建议长数字加密可以让用户自定义脱敏的位数，只有二代身份证号脱敏加密的话，太具有针对性了，像银行卡号、工号之类的可以传参设置脱敏位数

目前是支持用户自定义自己的脱敏实现方法，不同的卡，可以实现不同的脱敏方法。
这种应该是符合你的预期的。

**Comment by lyl9816** [comment]
> > 建议长数字加密可以让用户自定义脱敏的位数，只有二代身份证号脱敏加密的话，太具有针对性了，像银行卡号、工号之类的可以传参设置脱敏位数
> 
> 目前是支持用户自定义自己的脱敏实现方法，不同的卡，可以实现不同的脱敏方法。
> 这种应该是符合你的预期的。

嗯嗯是可以的~我加了自定义方法

**Comment by houbb** [comment]
v1.2.1 已支持。
