### ISSUE TITLE
json 依赖库选型问题?

### ISSUE THREAD

**Issue by scruel** [houbb/sensitive#10]
fastjson 频爆 CVE，请问可以考虑更换为更加被广泛应用的 jackson 三方库用作 json 处理吗？（目前是为了防止安全问题，项目的 desJson 相关方法都不敢在项目中使用。）
另外项目是否可以基于 java 8 来调整一些相关代码。
谢谢。

**Comment by houbb** [comment]
（1）json 选型问题
平时工作中接触的最多的还是 FASTJSON，所以当时就基于这个实现了，其实可以使用 `desCopy()` 深度拷贝，然后选择自己喜欢的三方 json
（2）安全问题
fastjson 频爆 CVE，这个确实是存在，所以目前依赖的是 `1.2.70`。（个人感觉是用的人多，所以问题发现的也多。其实 GJSON 也有类似的问题。）
这个要看具体的应用场景，一般不用太过焦虑。
（3）jdk8 问题
目前使用 jdk7，主要是为了兼容市面上大部分的生产环境的 jdk 版本。
越大的项目，历史包袱越重，过段时间可以考虑改为 jdk8。

**Comment by houbb** [comment]
也非常感谢上面的建议，祝使用愉快~~

**Comment by scruel** [comment]
> 
> 
> 也非常感谢上面的建议，祝使用愉快~~

问题不大，上面的几个点已经自己在改了，不过部分的改动可能会不做 PR 了，因为改动比较大。
