### ISSUE TITLE
如果要将某个字段加密支持吗?

### ISSUE THREAD

**Issue by objectboy2016** [houbb/sensitive#17]
比如不是将phone字段按照176****456输出, 而是将phone加密,   这样是否支持呢

**Comment by houbb** [comment]
这个项目是为了日志脱敏，你也可以自定义脱敏策略，实际是加密。
加密的算法很多，应用场景不同



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: objectboy2016 ***@***.***&gt;
发送时间: 2022年8月19日 17:44
收件人: houbb/sensitive ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [houbb/sensitive] 如果要讲某个字段加密呢  支持吗 (Issue #17)





 
比如要将phone加密是否支持呢
