### ISSUE TITLE
性能消耗怎么样?

### ISSUE THREAD

**Issue by objectboy2016** [houbb/sensitive#19]
我们现在单条日志在2M左右 , 而且量特别大,  请问性能损耗怎么样?

**Comment by houbb** [comment]
json 的方式性能损耗不大。
一条日志2Mb是不合理的。一天500W条日志就需要1万G 的磁盘。不必要的信息可以不打印。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: objectboy2016 ***@***.***&gt;
发送时间: 2022年9月16日 17:12
收件人: houbb/sensitive ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [houbb/sensitive] 性能消耗怎么样? (Issue #19)





 
我们现在单条日志在2M左右 , 而且量特别大,  请问性能损耗怎么样?

**Comment by houbb** [comment]
可以做一下压测，企业级单个应用压测下来，性能损耗 1% 以内。
