### ISSUE TITLE
threadLocal好像一直都没有remove？

### ISSUE THREAD

**Issue by sujiangtao123** [houbb/sensitive#23]
![image](https://github.com/houbb/sensitive/assets/55537020/206338f2-629c-46ea-9627-27906771343f)

作者好，这个脱敏我借鉴了很多，但是这里有一个StrategyBufferThreadLocal  这个一个实现脱敏的缓存
本质其实是使用了ThreadLocal，但是好像从来没有记性过remove，是在哪里remove掉我没发现吗？

**Comment by houbb** [comment]
这个只是一个对比实现，本来目的是为了验证不做对象创建提升性能，实际上压测性能差异不明显。
所以每次新建更加简单直接。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Marinated Egg ***@***.***&gt;
发送时间: 2023年10月11日 10:33
收件人: houbb/sensitive ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [houbb/sensitive] threadLocal好像一直都没有remove？ (Issue #23)





 

 
作者好，这个脱敏我借鉴了很多，但是这里有一个StrategyBufferThreadLocal  这个一个实现脱敏的缓存
 本质其实是使用了ThreadLocal，但是好像从来没有记性过remove，是在哪里remove掉我没发现吗？

**Comment by sujiangtao123** [comment]
好的感谢，我目前就是也直接新建了
