### ISSUE TITLE
在clone项目到本地的时候 引入大部分依赖报错，预计是缺少相应的setting地址导致，能否提供对应的setting文件？

### ISSUE THREAD

**Issue by codecheng199** [houbb/sensitive#27]
在clone项目到本地的时候 引入大部分依赖报错，预计是缺少相应的setting地址导致，能否提供对应的setting文件？

**Comment by houbb** [comment]
具体错误信息是什么？按理说不缺少包才对



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: codecheng199 ***@***.***&gt;
发送时间: 2023年11月21日 16:13
收件人: houbb/sensitive ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [houbb/sensitive] 在clone项目到本地的时候 引入大部分依赖报错，预计是缺少相应的setting地址导致，能否提供对应的setting文件？ (Issue #27)





 
在clone项目到本地的时候 引入大部分依赖报错，预计是缺少相应的setting地址导致，能否提供对应的setting文件？

**Comment by codecheng199** [comment]
could not transfer artifact https://xx ， 我删除了repository 后，将爆红依赖删除再撤回 后拉下来了，可能是仓库中lastupdate 文件导致，已解决。
