### ISSUE TITLE
chars-scan 的源码在哪里？

### ISSUE THREAD

**Issue by misaya98** [houbb/sensitive#28]
chars-scan 的源码在哪里？

**Comment by houbb** [comment]
暂不开源。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: misaya ***@***.***&gt;
发送时间: 2024年1月24日 15:14
收件人: houbb/sensitive ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [houbb/sensitive] chars-scan 的源码在哪里？ (Issue #28)





 
chars-scan 的源码在哪里？
