### ISSUE TITLE
y一些使用上的问题

### ISSUE THREAD

**Issue by qq123456789101112** [houbb/sensitive#30]
怎么对脱敏规则进行自定义扩展？例如手机号，目前框架只支持11位的手机号，对加了86开头、或者港澳电话、座机这些，可以自定义扩展么？又例如姓名，目前代码里面是写死了3000多个单姓字典做匹配，怎么对复姓、小数名族的姓名做规则扩展？

**Comment by houbb** [comment]
如果是注解，注解是支持自定义策略的。
