### ISSUE TITLE
sensitive-log4j2 识别格式

### ISSUE THREAD

**Issue by ppliang13** [houbb/sensitive#31]
我在使用这个进行脱敏时，这个无法对标签`<phone>12326877231</phone> `进行脱敏吧

**Comment by ppliang13** [comment]
进行重写脱敏 SensitiveRewritePolicy 285M
beginTime: 14:28:27.878
endTime: 14:28:42.563
共计用时：14685 毫秒

正常日志输出 285M
beginTime: 14:29:55.276
endTime: 14:29:56.485
共计用时：1209 毫秒

费时相差12倍

**Comment by houbb** [comment]
支持的，可能需要定义一下前缀字符，比如  `>`。
1) 日志可以分类，业务支持一般需要脱敏，其他的没必要指定。
2) 性能对比的话，可以考虑横比如自己实现一个正则之类的，然后用业务随机日志，真实对比一下看看效果。对比验证看下
