### ISSUE TITLE
针对单个字段脱敏有办法指定策略生效条件吗？

### ISSUE THREAD

**Issue by HikariNoSenritsu** [houbb/sensitive#4]
//想在这种情况下指定策略生效条件 eg. ConditionFooEmail
    final String email = "123456@qq.com";
    IStrategy strategy = new StrategyEmail();
    final String emailSensitive = (String) strategy.des(email, null);
    System.out.println("脱敏后的邮箱：" + emailSensitive);

**Comment by houbb** [comment]
参见 [自定义脱敏策略生效的场景](https://github.com/houbb/sensitive#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%84%B1%E6%95%8F%E7%AD%96%E7%95%A5%E7%94%9F%E6%95%88%E7%9A%84%E5%9C%BA%E6%99%AF)

如果只是针对一个字符串，自己判断即可，使用 ICondition 反而比较麻烦。
