### ISSUE TITLE
如果子类用SensitiveEntry标识后，当子类为null，会报npe

### ISSUE THREAD

**Issue by ChanglongYe** [houbb/sensitive#5]
class Father{
  @SensitiveEntry
   private Child c;
}
当c==null时，SensitiveUtil.desCopy(father类)会报npe

**Comment by houbb** [comment]
你使用的是哪一个版本？

我用 v0.0.10 测试是通过的。

[SensitiveUtilTest.java](https://github.com/houbb/sensitive/blob/master/sensitive-test/src/test/java/com/github/houbb/sensitive/test/core/util/SensitiveUtilTest.java)
