### ISSUE TITLE
基于SLF4j实现拦截器形式的统一脱敏

### ISSUE THREAD

**Issue by jinianjun** [houbb/sensitive#8]
大佬好，对于大部分老系统，已有大量的日志打印，如果每个去修改调用脱敏方法，工作量非常大。是否可以考虑基于SLF4j实现拦截器形式的统一脱敏？目标是尽量不改动原有代码。

**Comment by houbb** [comment]
一直有这个想法，无奈最近比较忙。


实现的话估计会新建一个项目。&nbsp;


基于注解，是为了不限于 slf4j，可以更广泛的使用。


后续有时间的话会实现基于日志框架的脱敏实现。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jinianjun <notifications@github.com&gt;
发送时间: 2020年11月2日 15:46
收件人: houbb/sensitive <sensitive@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[houbb/sensitive] 基于SLF4j实现拦截器形式的统一脱敏 (#8)





 
大佬好，对于大部分老系统，已有大量的日志打印，如果每个去修改调用脱敏方法，工作量非常大。是否可以考虑基于SLF4j实现拦截器形式的统一脱敏？目标是尽量不改动原有代码。

**Comment by houbb** [comment]
v1.2.1 已支持。
